- name: Set up Flask environment
  hosts: webservers
  become: yes

  tasks:
    - name: Update and Upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist
        force_apt_get: yes

    - name: Install python3, python3-pip, and python3-venv
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
        state: present

    - name: Create a virtual environment for Flask
      command: python3 -m venv /opt/flask_venv

    - name: Install Flask via pip in the virtual environment
      command: /opt/flask_venv/bin/pip install flask

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Run Flask app in Docker
      command: docker build -t flask-calculator /mnt/c/Users/hossa/Desktop/DevOps/my-env/flask_calculator

    - name: Start the Flask application
      command: /opt/flask_venv/bin/python /mnt/c/Users/hossa/Desktop/DevOps/my-env/flask_calculator/app.py
      args:
        chdir: /mnt/c/Users/hossa/Desktop/DevOps/my-env/flask_calculator
