name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Step 2: Set Up Docker with Login, Build, and Run Image
      - name: Set Up Docker
        run: |
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            docker build -t flask-calculator .
            docker run -d -p 5000:5000 flask-calculator
